# Generated by Django 5.1.1 on 2024-12-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('curp', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('puesto', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
