# Generated by Django 5.1.1 on 2024-12-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_empleado', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('num_telefono', models.PositiveIntegerField()),
                ('correo_electronico', models.EmailField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
    ]
