# Generated by Django 5.1.1 on 2024-12-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_venta', models.PositiveIntegerField()),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=50)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_sucursal', models.PositiveIntegerField()),
            ],
        ),
    ]
