# Generated by Django 5.1.1 on 2024-12-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id_provedor', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=50)),
                ('num_celular', models.PositiveIntegerField()),
                ('fecha_de_recorrido', models.DateField()),
                ('id_sucursal', models.PositiveIntegerField()),
            ],
        ),
    ]
